PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class PersonaController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result();
            ML.Persona persona = new ML.Persona();

            result = BL.Persona.GetAll();

            if (result.Correct)
            {
                persona.Personas = result.Objects;
                return View(persona);
            }

            return View(persona);
        }


        [HttpGet]
        public ActionResult Form(int? IdPersona)
        {
            ML.Result result = new ML.Result();
            ML.Persona persona = new ML.Persona();

            if (IdPersona != null)
            {
                result = BL.Persona.GetById(IdPersona.Value);
                if (result.Correct)
                {
                    persona = (ML.Persona)result.Object;
                    return View(persona);
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar la informacion del registro " + result.ErrorMessage;
                }
                return PartialView("Modal");
            }
            else
            {
                return View(persona);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Persona persona)
        {
            ML.Result result = new ML.Result();
            int IdPersona = persona.IdPersona;

            if (IdPersona > 0)
            {
                //UPDATE
                result = BL.Persona.Update(persona);
                if (result.Correct)
                {
                    ViewBag.Message = "Persona actualizada con exito";
                }
                else
                {
                    ViewBag.Message = "Error al actualizar el registro";
                }


            }
            else
            {
                result = BL.Persona.Add(persona);
                if (result.Correct)
                {
                    ViewBag.Message = "Persona agregada con exito";
                }
                else
                {
                    ViewBag.Message = "Error al agregar el registro";
                }
            }

            return PartialView("Modal");

        }

        [HttpGet]
        public ActionResult Delete(int IdPersona)
        {
            ML.Result result = BL.Persona.Delete(IdPersona);
            if (result.Correct)
            {
                ViewBag.Message = "Persona eliminada con exito";
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al intentar eliminar el registro " + result.ErrorMessage;
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Persona/Form.cshtml
@model ML.Persona
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>REGISTRO DE PERSONAS</h2>
<div class="row">
    <div class="col-12">
        <h5>Ingrese los datos de la persona:</h5>
    </div>
</div>
</hr>

@using (Html.BeginForm("Form", "Persona", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-1" style="display: none;">
            @Html.TextBoxFor(model => model.IdPersona, new { @class = "hidden form-control", autocomplete = "off" })
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.Nombre, "Nombre(s): ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.Nombre, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.ApellidoPaterno, "Apellido Paterno:")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.ApellidoMaterno, "Apellido Materno(Opcional): ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.FechaNacimiento, "Fecha de Nacimiento(YYYY-MM-DD): ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, null, new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="row">

        <div class="col-md-3">
            @Html.LabelFor(model => model.Sexo, "Sexo(Hombre/Mujer): ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.Sexo, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.Sexo, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.EstadoNacimiento, "Estado de Nacimiento: ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.EstadoNacimiento, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.EstadoNacimiento, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.Direccion.IdDireccion, "ID Direccion: ")
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.Direccion.IdDireccion, new { @class = "form-control", autocomplete = "off" })
                @Html.ValidationMessageFor(model => model.Direccion.IdDireccion, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-3">
            @Html.LabelFor(model => model.CURP)
            <div class="input-group mb-2">
                <span class="input-group-text"><i class="bi bi-controller"></i></span>
                @Html.TextBoxFor(model => model.CURP, new { @class = "form-control", autocomplete = "off" , disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.CURP, null, new { @class = "text-danger" })
            </div>
        </div>

    </div>


    <div class="row">
        <div class="glyphicon-up">
            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    @Html.ActionLink("Regresar", "GetAll", "Persona", htmlAttributes: new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
}

PL/Views/Persona/GetAll.cshtml
@model ML.Persona
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PERSONAS REGISTRADAS</h2>

<div style="float:right;">
    @Html.ActionLink("Agregar", "Form", "Persona", htmlAttributes: new { @class = "btn btn-success" })
</div>

<br />
<br />
<br />

<table class="table table-hover table-striped table-bordered table-responsive" id="table_usuarios">
    <thead>
        <tr class="table-secondary">
            <td style="text-align:center">Editar</td>
            <td style="display :none;">id</td>
            <td style="text-align:center">Nombre Completo</td>
            <td style="text-align:center">Fecha de Nacimiento</td>
            <td style="text-align:center">Sexo</td>
            <td style="text-align:center">Estado de Nacimiento</td>
            <td style="text-align:center">Direccion</td>
            <td style="text-align:center">CURP</td>
            <td style="text-align:center">Eliminar</td>


        </tr>
    </thead>
    <tbody>
        @foreach (ML.Persona persona in Model.Personas)
        {
            <tr>
                <td style="text-align: center; vertical-align: middle;"><a class="btn btn-warning glyphicon  glyphicon glyphicon-cog" href="@Url.Action("Form", "Persona", new { IdPersona = persona.IdPersona})"><i class="bi bi-pencil-square" style="color: ivory"></i></a></td>
                <td style="display :none;">@persona.IdPersona </td>
                <td style="text-align:center">@persona.NombreCompleto</td>
                <td style="text-align:center">@persona.FechaNacimiento</td>
                <td style="text-align:center">@persona.Sexo</td>
                <td style="text-align:center">@persona.EstadoNacimiento</td>
                <td style="text-align:center">@persona.DireccionCompleta</td>
                <td style="text-align:center">@persona.CURP</td>
                <td style="text-align: center; vertical-align: middle;"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Persona", new { idPersona = persona.IdPersona})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><i class="bi bi-eraser-fill" style="color: mintcream"></i></a></td>
            </tr>
        }

    </tbody>
</table>

PL/Views/Persona/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message"</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "GetAll", "Persona", htmlAttributes: new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>
    $('#Modal').modal();
</script>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Personas", "GetAll", "Persona")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>